services:
  - type: web
    name: madrid-dashboard
    env: static
    buildCommand: echo done
    staticPublishPath: ./dashboard
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
